name: ⚙️ Test Action

on: [pull_request, push]

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ⎔ Run Action
        uses: ./
