name: ⚙️ Test Action

on: [pull_request, push]

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'

      - name: 📥 npm install
        uses: bahmutov/npm-install@v1.8.5

      - name: ⎔ Run Action No Circular Deps
        id: nocirculardeps
        uses: ./
    
    outputs:
      branchCircularDepsFile: ${{ steps.nocirculardeps.outputs.branchCircularDepsFilePath }}
      newCircularDepsFile: ${{ steps.nocirculardeps.outputs.newCircularDepsFilePath }}

  comment-output: 
    needs: test

    steps:
      - name: Comment PR with branch circular deps file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ${{needs.test.outputs.branchCircularDepsFile}}
      - name: Comment PR with new circular deps file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ${{needs.test.outputs.newCircularDepsFile}}

    
